[package]
name = "mlbt"
version = "0.0.2"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2018"

[workspace]
members = [".", "api"]

[dependencies]
mlb-api = {path = "api/", version = "0.0.1"}
chrono = "0.4"
tui = "0.14"
termion = "1.5"
lazy_static = "1.4.0"
