[package]
name = "mlbt"
version = "0.0.1"
authors = ["Andrew Schneider <andjschneider@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlb-api = {path = "api/"}
chrono = "0.4"
tui = "0.14"
termion = "1.5"
lazy_static = "1.4.0"
